### PR TITLE
Feature/adminaccess

### PR DESCRIPTION
**Pull request by Anth0nyPereira**

### CODE REVIEW

**Comment by Anth0nyPereira** [comment]
Hey guys, 
This version of our branch is stable, so we're requesting a PR to the develop branch. Tell us if everything is okay, and accept it, please. We appreciate it.

Keep going the good work.

**Comment by JoaoTS20** [comment]
> Hey guys,
> This version of our branch is stable, so we're requesting a PR to the develop branch. Tell us if everything is okay, and accept it, please. We appreciate it.
> 
> Keep going the good work.

There is a mistake with RiderRepository Test in this new Branch
It may be  from the pom.xml file.

**Comment by Anth0nyPereira** [comment]
So, a little update, I changed the AdminRepositoryTest to be one that uses TestContainers, and even though it does not run in my pc, it works in the CI.

**Comment by Anth0nyPereira** [comment]
Another note, though, is that it's not passing the quality gate - one of the things that I will change is the security hotspot, using a larger digest in the PasswordEncryptor.

**Comment by JoaoTS20** [comment]
> Another note, though, is that it's not passing the quality gate - one of the things that I will change is the security hotspot, using a larger digest in the PasswordEncryptor.

Alright, good job I will take that into consideration in my review.
Try to do that change quickly.

**Review by JoaoTS20 — APPROVED** [review]

**Comment by Wei93442** [comment]
I have implemented 30 tests. Each controller and service was tested.

The results were reported using the Jacoco plugin. However, some classes had 0 coverage for unknown reasons, even though all their methods had been tested. There were also classes where only some of the methods were covered, and other methods had 0 coverage even though they passed all the tests.

We tried to find the problem and fix it, but we didn't.

image
image
For example, all tests of the product controller passed, but it still with 0 coverage.

**Review by JoaoTS20 — DISMISSED** [review]

**Review by JoaoTS20 — APPROVED** [review]

**Pull request merged**
