### PR TITLE
Feature/add to cart purchase

### PR DESCRIPTION
**Pull request by Wei93442**
implemented 'add a product to a cart' and 'purchase'
for now, I can't test the endpoint of purchase, I will test them after I deploy them to the VM

### CODE REVIEW

**Comment by Wei93442** [comment]
I have implemented 30 tests. Each controller and service was tested.

The results were reported using the Jacoco plugin. However, some classes had 0 coverage for unknown reasons, even though all their methods had been tested. There were also classes where only some of the methods were covered, and other methods had 0 coverage even though they passed all the tests.

We tried to find the problem and fix it, but we didn't.

image
image

For example, all tests of the product controller passed, but it still with 0 coverage.

**Comment by Wei93442** [comment]
image
Although we had some problems with the Jacoco plugin, all tests passed, so we think is acceptable.

**Comment by JoaoTS20** [comment]
> I have implemented 30 tests. Each controller and service was tested.
> 
> The results were reported using the Jacoco plugin. However, some classes had 0 coverage for unknown reasons, even though all their methods had been tested. There were also classes where only some of the methods were covered, and other methods had 0 coverage even though they passed all the tests.
> 
> We tried to find the problem and fix it, but we didn't.
> 
> image
> image
> 
> For example, all tests of the product controller passed, but it still with 0 coverage.

Alright, good job I will take that into consideration in my review.
We will need to address that sudden problem quickly in the next days.

**Review by JoaoTS20 — APPROVED** [review]

**Review by HugoDinisOF — APPROVED** [review]
Good job @Wei93442 keep working well

**Pull request merged**
